name: Build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0
          bundler-cache: true
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '>1.4.0'
      - name: Install Dashing
        run: |
          go install github.com/technosophos/dashing@latest
      - name: Build docset
        run: |
          TAG=$(cat tag.txt)
          git clone https://github.com/bridgetownrb/bridgetown.git source
          cd source
          git checkout tags/$TAG -b build
          cd bridgetown-website
          bundle install
          yarn install
          BRIDGETOWN_ENV=production bin/bridgetown deploy
          cd output
          find . -name index.html -exec rm {} +
          ../../../transform.rb
          cp ../../../dashing.json ../../../icon.png .
          dashing build bridgetown
      - name: Upload docset
        uses: actions/upload-artifact@v3
        with:
          name: bt.docset
          path: source/bridgetown-website/output/bt.docset
